version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\DDRBoxman\crank

environment:
  GOPATH: c:\gopath

install:
  - set PATH=C:\MinGW\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v -t -d ./...

build_script:
  - go test -v -race ./...
